<a href="https://colab.research.google.com/github/mehraanjali/SalaryPrediction_LinearRegression_and_Using_Modules_Like_word2Number_Pickle_JobLib/blob/main/SalaryPrediction_LinearRegression_and_Using_Modules_Like_word2Number_Pickle_JobLib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
d = pd.read_csv("/content/hiring.csv")
d

experience  test_score_out_of_10  interview_score_out_of_10  \
0        NaN                   8.0                          9   
1        NaN                   8.0                          6   
2       five                   6.0                          7   
3        two                  10.0                         10   
4      seven                   9.0                          6   
5      three                   7.0                         10   
6        ten                   NaN                          7   
7     eleven                   7.0                          8   

   salary_in_Dollar  
0             50000  
1             45000  
2             60000  
3             65000  
4             70000  
5             62000  
6             72000  
7             80000

**Data Preprocessing**

In [ ]:
d.experience = d.experience.fillna('zero')
d

experience  test_score_out_of_10  interview_score_out_of_10  \
0       zero                   8.0                          9   
1       zero                   8.0                          6   
2       five                   6.0                          7   
3        two                  10.0                         10   
4      seven                   9.0                          6   
5      three                   7.0                         10   
6        ten                   NaN                          7   
7     eleven                   7.0                          8   

   salary_in_Dollar  
0             50000  
1             45000  
2             60000  
3             65000  
4             70000  
5             62000  
6             72000  
7             80000

In [ ]:
import math
mean = math.floor(d.test_score_out_of_10.mean())
mean

7

In [ ]:
d.test_score_out_of_10 = d.test_score_out_of_10.fillna(mean)
d

experience  test_score_out_of_10  interview_score_out_of_10  \
0       zero                   8.0                          9   
1       zero                   8.0                          6   
2       five                   6.0                          7   
3        two                  10.0                         10   
4      seven                   9.0                          6   
5      three                   7.0                         10   
6        ten                   7.0                          7   
7     eleven                   7.0                          8   

   salary_in_Dollar  
0             50000  
1             45000  
2             60000  
3             65000  
4             70000  
5             62000  
6             72000  
7             80000

**Changing word into numbers using word2number module.**

In [ ]:
pip install word2number

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5582 sha256=8ee92c18e6c2da2954f93d0b3a97f8c6841b45a25115954de934d94091fab625
  Stored in directory: /root/.cache/pip/wheels/a0/4a/5b/d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number


In [ ]:
from word2number import w2n

In [ ]:
d.experience = d.experience.apply(w2n.word_to_num)
d

experience  test_score_out_of_10  interview_score_out_of_10  \
0           0                   8.0                          9   
1           0                   8.0                          6   
2           5                   6.0                          7   
3           2                  10.0                         10   
4           7                   9.0                          6   
5           3                   7.0                         10   
6          10                   7.0                          7   
7          11                   7.0                          8   

   salary_in_Dollar  
0             50000  
1             45000  
2             60000  
3             65000  
4             70000  
5             62000  
6             72000  
7             80000

**Applying Linear regression model to predict Salary in Dollar using the other 3 factors.**

In [ ]:
from sklearn import linear_model

reg = linear_model.LinearRegression()

In [ ]:
reg.fit(d[['experience', 'test_score_out_of_10',	'interview_score_out_of_10']], d.salary_in_Dollar)

LinearRegression()

In [ ]:
reg.predict([[2, 9, 6]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

**Saving model using pickle**

In [ ]:
import pickle

**binary data - wb (write binary)**

In [ ]:
with open('model_pickle','wb') as f:
  pickle.dump(reg,f)

 **To use the saved model**

**rb - read binary**

In [ ]:
with open('model_pickle','rb') as f:
  mp = pickle.load(f)

In [ ]:
mp.predict([[2, 9, 6]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

**JobLib**

*it is more benificial for large number of numpy arrays*

*In jupiter it is - from sklearn import joblib*

In [ ]:
import joblib

**To save**

In [ ]:
joblib.dump(reg,'model_joblib')

['model_joblib']

**To retrieve**

In [ ]:
mj = joblib.load('model_joblib')

In [ ]:
mj.predict([[2, 9, 6]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])